title: Ben Phillips - Portfolio
author: Ben Phillips
email: benjamin.phillips22+portfolio@gmail.com
description: Ben Phillips - Data Scince, Machine Learning, Statistical Analysis, AI, Mathematics, Data Visualisation
url: "https://benjaminphillips22.github.io"
twitter_username: Ben_Phillips22
github_username:  benjaminphillips22
#google_analytics: UA-110543961-1

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap